# This workflow will install Python dependencies, run Asx Data Fetcher script to update the database
name: Asx Listings Fetcher

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */4 * * *"

jobs:
  Fetch_Asx_Listings:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip       
        if [ -f ./Ingestion/requirements.txt ]; then pip install -r ./Ingestion/requirements.txt; fi
    - name: Setup DB Connection Environment Variable
      run: |
        echo "asx_db=${{ secrets.asx_prod_db }}" >> $GITHUB_ENV
    - name: Fetch Data from Asx Listings Page
      run: |
        python3 start_fetcher.py
